name: Terraform
on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - main
jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5 # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v34

      - name: Terraform Apply
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: terraform apply -auto-approve
