name: Terraform
on:
  push:
    branches:
      - feature/*
      - dev
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4 # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.4

      - name: Checkout code
        uses: actions/checkout@v34

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
          TF_VAR_github_owner: ${{ secrets.GH_OWNER }}
        run: terraform apply -auto-approve
